### ISSUE TITLE
Show command flag

### ISSUE THREAD

**Issue by enlewof** [lemoony/snipkit#135]
Hi there,

A coworker of mine wanted a command flag to show the debug information before like the command is run.  He added it to pet, but looks like pet development stalled: https://github.com/knqyf263/pet/pull/142

Any chance this could be added to snipkit?  Low priority of course.

Thanks.

**Comment by lemoony** [comment]
Hey,

Just to make sure I understand your proposal: You want to show the script that would be executed (like with `snipkit print`) and then, if it looks good to you, either execute it or abort?

**Comment by enlewof** [comment]
No, more like a debug mode kind of deal just in case.  Like snipkit still does the exec but prints out the command it ran as well.

**Comment by lemoony** [comment]
Do yout want it printed on stdout or would the log file suffice? Printing the command to the logs if `-l debug` is enabled  should be one either way.

**Comment by enlewof** [comment]
Stdout would be ideal yeah.

**Comment by lemoony** [comment]
Hi @enlewof , i've just released Version 1.4.0 with two new flags for `exec`: `--print` and `--confirm`.

Does this work for you?
