### ISSUE TITLE
Default text editor seems to be "mvim"

### ISSUE THREAD

**Issue by JCPetrelli** [lemoony/snipkit#167]
Hi!
I noticed that when I try to edit my config file via:
`snipkit config edit`
I see that it's trying to open the file with "mvim" rather than my default editor (for example I have vim installed and not mvim)

**Error:
failed to open editor: mvim /Users/xxxxxxxx/Library/Application Support/snipkit/config.yaml: exec: "mvim": executable file not found in $PATH**

Would it be possible to use the default text editor of the system? Super repo btw!

**Comment by lemoony** [comment]
Hi @JCPetrelli ,

snipkit tries to use the default editor, actually. The behavior is documented:

_The default editor is defined by the `$VISUAL` or `$EDITOR` environment variables. This behavior can be overwritten by setting the editor field in the configuration file to a non-empty string, ...

Does this answer your question?

**Comment by JCPetrelli** [comment]
Hi @lemoony, 
Thanks for your answer, that covers it completely. It was actually a mistake from my side with the default `$EDITOR` on my machine. It works perfectly now, thank you!
