### ISSUE TITLE
fzf in snippet and command?

### ISSUE THREAD

**Issue by bdahan** [lemoony/snipkit#233]
Hi, thanks for this great manager!
I've managed to sync all my snippets from snippetslab successfully. is it possible to fzf the command (not only the snippet name)?
I'm using fish shell, what I'm trying to achieve is basically this https://github.com/aluxian/fish-pet with snipkit.
when invoking ctrl -s I can search my snippets using fzf.
Appreciate any help,
Benny

**Comment by lemoony** [comment]
Hi, thanks - much appreciated!

Not sure yet how that works, I'm gonna have a look at it.

**Comment by lemoony** [comment]
Support for a custom workflow with fzf made it into the v1.5.0 release. The documentation provides an example script:

https://lemoony.github.io/snipkit/v1.5.0/getting-started/fzf/
