### ISSUE TITLE
Add pet multiple parameter support

### ISSUE THREAD

**Issue by enlewof** [lemoony/snipkit#235]
Pet added multiple parameters in a later version (see https://github.com/knqyf263/pet/pull/290).  Would be awesome if snipkit could add support for that.  Currently, it just shows all the parameters as one line.

**Comment by lemoony** [comment]
Certainly, I'll have a look 👍 Hopefully no big deal

**Comment by lemoony** [comment]
Sorry this took so long. It's implemented an will be included in the next release.

**Comment by lemoony** [comment]
Released with v1.5.0 👍
